/*
 * NoticeReportPage.java
 *
 * Created on August 18, 2011, 10:47 AM
 */

package etracs2.rpt.report;

import com.rameses.rcp.ui.annotations.StyleSheet;

/**
 *
 * @author  jzamora
 */
@StyleSheet("etracs2/rpt/report/NoticeReportPage.style")
public class NoticeReportPage extends javax.swing.JPanel {
    
    /** Creates new form NoticeReportPage */
    public NoticeReportPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xActionBar1 = new com.rameses.rcp.control.XActionBar();
        jPanel1 = new javax.swing.JPanel();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        formPanel4 = new com.rameses.rcp.util.FormPanel();
        xRadio3 = new com.rameses.rcp.control.XRadio();
        xLookupField4 = new com.rameses.rcp.control.XLookupField();
        formPanel5 = new com.rameses.rcp.util.FormPanel();
        xRadio4 = new com.rameses.rcp.control.XRadio();
        xLookupField2 = new com.rameses.rcp.control.XLookupField();

        setLayout(new java.awt.BorderLayout());

        xActionBar1.setBorder(new com.rameses.rcp.control.border.XUnderlineBorder());
        xActionBar1.setName("formActions");
        add(xActionBar1, java.awt.BorderLayout.NORTH);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Notice of Assessment Initial Information");
        formPanel1.setBorder(xTitledBorder1);

        formPanel4.setCellpadding(new java.awt.Insets(0, 0, 0, 20));
        formPanel4.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        formPanel4.setShowCaption(false);
        xRadio3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xRadio3.setSelected(true);
        xRadio3.setText("By Taxpayer :");
        xRadio3.setCaption("By Taxpayer");
        xRadio3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xRadio3.setName("searchcriteria");
        xRadio3.setOpaque(false);
        xRadio3.setOptionValue("bytaxpayer");
        xRadio3.setShowCaption(false);
        formPanel4.add(xRadio3);

        xLookupField4.setCaption("Taxpayer");
        xLookupField4.setDepends(new String[] {"searchcriteria"});
        xLookupField4.setExpression("#{entityname}");
        xLookupField4.setHandler("lookupTaxpayer");
        xLookupField4.setName("taxpayer");
        xLookupField4.setPreferredSize(new java.awt.Dimension(250, 19));
        xLookupField4.setShowCaption(false);
        formPanel4.add(xLookupField4);

        formPanel1.add(formPanel4);

        formPanel5.setCellpadding(new java.awt.Insets(0, 0, 0, 20));
        formPanel5.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        formPanel5.setPadding(new java.awt.Insets(0, 5, 5, 5));
        formPanel5.setShowCaption(false);
        xRadio4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xRadio4.setText("By TD No. :");
        xRadio4.setCaption("By Taxpayer");
        xRadio4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xRadio4.setName("searchcriteria");
        xRadio4.setOpaque(false);
        xRadio4.setOptionValue("bytdno");
        xRadio4.setPreferredSize(new java.awt.Dimension(85, 15));
        xRadio4.setShowCaption(false);
        formPanel5.add(xRadio4);

        xLookupField2.setCaption("TD No.");
        xLookupField2.setDepends(new String[] {"searchcriteria"});
        xLookupField2.setDynamic(true);
        xLookupField2.setExpression("#{tdno}");
        xLookupField2.setHandler("lookupFAAS");
        xLookupField2.setName("faas");
        xLookupField2.setPreferredSize(new java.awt.Dimension(250, 19));
        xLookupField2.setShowCaption(false);
        formPanel5.add(xLookupField2);

        formPanel1.add(formPanel5);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 413, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        add(jPanel1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.util.FormPanel formPanel4;
    private com.rameses.rcp.util.FormPanel formPanel5;
    private javax.swing.JPanel jPanel1;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XLookupField xLookupField2;
    private com.rameses.rcp.control.XLookupField xLookupField4;
    private com.rameses.rcp.control.XRadio xRadio3;
    private com.rameses.rcp.control.XRadio xRadio4;
    // End of variables declaration//GEN-END:variables
    
}
