/*
 * ChangePinPage.java
 *
 * Created on August 6, 2012, 9:40 PM
 */

package etracs2.rpt.report.noticeofdelinquency;

import com.rameses.rcp.ui.annotations.StyleSheet;

/**
 *
 * @author  PRMF
 */
@StyleSheet("etracs2/rpt/report/noticeofdelinquency/NewDemandLettersPage.style")
public class CSDRPPage extends javax.swing.JPanel {
    
    /** Creates new form ChangePinPage */
    public CSDRPPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xButton2 = new com.rameses.rcp.control.XButton();
        xSeparator1 = new com.rameses.rcp.control.XSeparator();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        formPanel3 = new com.rameses.rcp.util.FormPanel();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xDateField2 = new com.rameses.rcp.control.XDateField();

        xButton2.setMnemonic('o');
        xButton2.setText("Ok");
        xButton2.setCaption("Ok");
        xButton2.setDefaultCommand(true);
        xButton2.setName("ok");

        org.jdesktop.layout.GroupLayout xSeparator1Layout = new org.jdesktop.layout.GroupLayout(xSeparator1);
        xSeparator1.setLayout(xSeparator1Layout);
        xSeparator1Layout.setHorizontalGroup(
            xSeparator1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 590, Short.MAX_VALUE)
        );
        xSeparator1Layout.setVerticalGroup(
            xSeparator1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 20, Short.MAX_VALUE)
        );

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Demand Letters Additional Information");
        xPanel1.setBorder(xTitledBorder1);

        formPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        formPanel2.setCaptionWidth(110);
        xTextField1.setCaption("Sold to");
        xTextField1.setName("entity.soldto");
        xTextField1.setPreferredSize(new java.awt.Dimension(200, 19));
        xTextField1.setRequired(true);
        formPanel2.add(xTextField1);

        xTextField2.setCaption("Sold to Address");
        xTextField2.setName("entity.soldtoaddress");
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField2.setRequired(true);
        formPanel2.add(xTextField2);

        xComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "filter" }));
        xComboBox1.setCaption("Civil Status");
        xComboBox1.setDynamic(true);
        xComboBox1.setExpression("#{caption}");
        xComboBox1.setImmediate(true);
        xComboBox1.setItems("civilstatuslist");
        xComboBox1.setName("civilstatus");
        xComboBox1.setPreferredSize(new java.awt.Dimension(150, 22));
        formPanel2.add(xComboBox1);

        formPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Spouse Info"));
        formPanel3.setCaptionWidth(110);
        formPanel3.setShowCaption(false);
        xTextField3.setCaption("Name");
        xTextField3.setDepends(new String[] {"civilstatus"});
        xTextField3.setName("entity.spousename");
        xTextField3.setPreferredSize(new java.awt.Dimension(200, 19));
        xTextField3.setRequired(true);
        formPanel3.add(xTextField3);

        xTextField4.setCaption("Address");
        xTextField4.setDepends(new String[] {"civilstatus"});
        xTextField4.setName("entity.spouseaddress");
        xTextField4.setPreferredSize(new java.awt.Dimension(200, 19));
        xTextField4.setRequired(true);
        formPanel3.add(xTextField4);

        formPanel2.add(formPanel3);

        xNumberField2.setCaption("Amount Sold");
        xNumberField2.setDepends(new String[] {"filter"});
        xNumberField2.setFieldType(Integer.class);
        xNumberField2.setName("entity.amountsold");
        xNumberField2.setPreferredSize(new java.awt.Dimension(80, 19));
        formPanel2.add(xNumberField2);

        xTextField5.setCaption("Sold to Address");
        xTextField5.setName("entity.soldtoaddress");
        xTextField5.setPreferredSize(new java.awt.Dimension(210, 19));
        xTextField5.setRequired(true);
        formPanel2.add(xTextField5);

        xDateField2.setCaption("OR Date");
        xDateField2.setDepends(new String[] {"af"});
        xDateField2.setFont(new java.awt.Font("Arial", 0, 12));
        xDateField2.setName("entity.ordate");
        xDateField2.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel2.add(xDateField2);

        org.jdesktop.layout.GroupLayout xPanel1Layout = new org.jdesktop.layout.GroupLayout(xPanel1);
        xPanel1.setLayout(xPanel1Layout);
        xPanel1Layout.setHorizontalGroup(
            xPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(xPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                .addContainerGap())
        );
        xPanel1Layout.setVerticalGroup(
            xPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(xPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, xPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(xButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(xSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(xPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(xSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(xButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel2;
    private com.rameses.rcp.util.FormPanel formPanel3;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XSeparator xSeparator1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    // End of variables declaration//GEN-END:variables
    
}
