/*
 * ChangePinPage.java
 *
 * Created on August 6, 2012, 9:40 PM
 */

package etracs2.rpt.report.noticeofdelinquency;

import com.rameses.rcp.ui.annotations.StyleSheet;

/**
 *
 * @author  PRMF
 */
@StyleSheet("etracs2/rpt/report/noticeofdelinquency/NewDemandLettersPage.style")
public class NewDemandLettersPage extends javax.swing.JPanel {
    
    /** Creates new form ChangePinPage */
    public NewDemandLettersPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        xDateField2 = new com.rameses.rcp.control.XDateField();
        xButton2 = new com.rameses.rcp.control.XButton();
        xSeparator1 = new com.rameses.rcp.control.XSeparator();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Demand Letters Information");
        formPanel2.setBorder(xTitledBorder1);
        formPanel2.setCaptionWidth(105);
        xComboBox3.setAllowNull(false);
        xComboBox3.setCaption("Doc Type");
        xComboBox3.setDynamic(true);
        xComboBox3.setExpression("#{description}");
        xComboBox3.setImmediate(true);
        xComboBox3.setItems("doctypelist");
        xComboBox3.setName("doctype");
        xComboBox3.setPreferredSize(new java.awt.Dimension(0, 22));
        formPanel2.add(xComboBox3);

        xComboBox1.setCaption("Filter By");
        xComboBox1.setDepends(new String[] {"doctype"});
        xComboBox1.setDynamic(true);
        xComboBox1.setExpression("#{caption}");
        xComboBox1.setImmediate(true);
        xComboBox1.setItems("filterlist");
        xComboBox1.setName("filter");
        xComboBox1.setPreferredSize(new java.awt.Dimension(150, 22));
        formPanel2.add(xComboBox1);

        xNumberField2.setCaption("Value");
        xNumberField2.setDepends(new String[] {"filter"});
        xNumberField2.setFieldType(Integer.class);
        xNumberField2.setName("entity.value");
        xNumberField2.setPreferredSize(new java.awt.Dimension(80, 19));
        formPanel2.add(xNumberField2);

        xDateField2.setCaption("Txn Date ");
        xDateField2.setDepends(new String[] {"af"});
        xDateField2.setFont(new java.awt.Font("Arial", 0, 12));
        xDateField2.setName("entity.billdate");
        xDateField2.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel2.add(xDateField2);

        xButton2.setMnemonic('n');
        xButton2.setText("Next");
        xButton2.setCaption("Next");
        xButton2.setDefaultCommand(true);
        xButton2.setName("next");

        org.jdesktop.layout.GroupLayout xSeparator1Layout = new org.jdesktop.layout.GroupLayout(xSeparator1);
        xSeparator1.setLayout(xSeparator1Layout);
        xSeparator1Layout.setHorizontalGroup(
            xSeparator1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 391, Short.MAX_VALUE)
        );
        xSeparator1Layout.setVerticalGroup(
            xSeparator1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 20, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(xSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                    .add(formPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, xButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 262, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(xSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(xButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel2;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    private com.rameses.rcp.control.XSeparator xSeparator1;
    // End of variables declaration//GEN-END:variables
    
}
