/*
 * ChangePinPage.java
 *
 * Created on August 6, 2012, 9:40 PM
 */

package etracs2.rpt.report.noticeofdelinquency;

import com.rameses.rcp.ui.annotations.StyleSheet;

/**
 *
 * @author  PRMF
 */
@StyleSheet("etracs2/rpt/report/noticeofdelinquency/NewDemandLettersPage.style")
public class NOPASPage extends javax.swing.JPanel {
    
    /** Creates new form ChangePinPage */
    public NOPASPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xDateField2 = new com.rameses.rcp.control.XDateField();
        xDateField3 = new com.rameses.rcp.control.XDateField();
        xDateField4 = new com.rameses.rcp.control.XDateField();
        xDateField5 = new com.rameses.rcp.control.XDateField();
        xDateField6 = new com.rameses.rcp.control.XDateField();
        xButton2 = new com.rameses.rcp.control.XButton();
        xSeparator1 = new com.rameses.rcp.control.XSeparator();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Demand Letters Additional Information");
        formPanel2.setBorder(xTitledBorder1);
        formPanel2.setCaptionWidth(110);
        xTextField1.setText("entity.newspapername");
        xTextField1.setCaption("News Paper Name");
        xTextField1.setName("entity.newspapername");
        xTextField1.setPreferredSize(new java.awt.Dimension(200, 19));
        xTextField1.setRequired(true);
        formPanel2.add(xTextField1);

        xTextField2.setCaption("Auction Address");
        xTextField2.setName("entity.auctionaddress");
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField2.setRequired(true);
        formPanel2.add(xTextField2);

        xDateField2.setCaption("Auction Date");
        xDateField2.setDepends(new String[] {"af"});
        xDateField2.setFont(new java.awt.Font("Arial", 0, 12));
        xDateField2.setName("entity.auctiondate");
        xDateField2.setPreferredSize(new java.awt.Dimension(120, 19));
        xDateField2.setRequired(true);
        formPanel2.add(xDateField2);

        xDateField3.setCaption("Auction Date");
        xDateField3.setDepends(new String[] {"af"});
        xDateField3.setFont(new java.awt.Font("Arial", 0, 12));
        xDateField3.setName("entity.publisheddate1");
        xDateField3.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel2.add(xDateField3);

        xDateField4.setCaption("Auction Date");
        xDateField4.setDepends(new String[] {"af"});
        xDateField4.setFont(new java.awt.Font("Arial", 0, 12));
        xDateField4.setName("entity.publisheddate2");
        xDateField4.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel2.add(xDateField4);

        xDateField5.setCaption("Auction Date");
        xDateField5.setDepends(new String[] {"af"});
        xDateField5.setFont(new java.awt.Font("Arial", 0, 12));
        xDateField5.setName("entity.publisheddate3");
        xDateField5.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel2.add(xDateField5);

        xDateField6.setCaption("Auction Date");
        xDateField6.setDepends(new String[] {"af"});
        xDateField6.setFont(new java.awt.Font("Arial", 0, 12));
        xDateField6.setName("entity.publisheddate4");
        xDateField6.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel2.add(xDateField6);

        xButton2.setMnemonic('o');
        xButton2.setText("Ok");
        xButton2.setCaption("Ok");
        xButton2.setDefaultCommand(true);
        xButton2.setName("ok");

        org.jdesktop.layout.GroupLayout xSeparator1Layout = new org.jdesktop.layout.GroupLayout(xSeparator1);
        xSeparator1.setLayout(xSeparator1Layout);
        xSeparator1Layout.setHorizontalGroup(
            xSeparator1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 391, Short.MAX_VALUE)
        );
        xSeparator1Layout.setVerticalGroup(
            xSeparator1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 20, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(xSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, xButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, formPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 262, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(xSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(xButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel2;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XDateField xDateField3;
    private com.rameses.rcp.control.XDateField xDateField4;
    private com.rameses.rcp.control.XDateField xDateField5;
    private com.rameses.rcp.control.XDateField xDateField6;
    private com.rameses.rcp.control.XSeparator xSeparator1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    // End of variables declaration//GEN-END:variables
    
}
