/*
 * ListPage.java
 *
 * Created on August 18, 2011, 8:34 PM
 */

package etracs2.rpt.report.noticeofdelinquency;

/**
 *
 * @author  jzamora
 */
public class SettingsPage extends javax.swing.JPanel {
    
    /** Creates new form ListPage */
    public SettingsPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xActionBar1 = new com.rameses.rcp.control.XActionBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        xCheckBox1 = new com.rameses.rcp.control.XCheckBox();
        xCheckBox2 = new com.rameses.rcp.control.XCheckBox();
        xCheckBox3 = new com.rameses.rcp.control.XCheckBox();
        xCheckBox4 = new com.rameses.rcp.control.XCheckBox();
        xCheckBox5 = new com.rameses.rcp.control.XCheckBox();
        xCheckBox6 = new com.rameses.rcp.control.XCheckBox();
        xCheckBox7 = new com.rameses.rcp.control.XCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        xCheckBox8 = new com.rameses.rcp.control.XCheckBox();

        setLayout(new java.awt.BorderLayout());

        xActionBar1.setBorder(new com.rameses.rcp.control.border.XUnderlineBorder());
        xActionBar1.setDepends(new String[] {"selectedItem"});
        xActionBar1.setName("formActions");
        add(xActionBar1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.setLayout(null);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Notice of Delinquency Settings");
        jPanel2.setBorder(xTitledBorder1);
        xCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox1.setText("Notice of Delinquency");
        xCheckBox1.setCheckValue(1);
        xCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox1.setName("entity.noticeofdelinquency");
        xCheckBox1.setUncheckValue(0);
        jPanel2.add(xCheckBox1);
        xCheckBox1.setBounds(40, 50, 260, 15);

        xCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox2.setText("Second Tracer");
        xCheckBox2.setCheckValue(1);
        xCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox2.setName("entity.secondtracer");
        xCheckBox2.setUncheckValue(0);
        jPanel2.add(xCheckBox2);
        xCheckBox2.setBounds(40, 70, 260, 15);

        xCheckBox3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox3.setText("Final Demand");
        xCheckBox3.setCheckValue(1);
        xCheckBox3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox3.setName("entity.finaldemand");
        xCheckBox3.setUncheckValue(0);
        jPanel2.add(xCheckBox3);
        xCheckBox3.setBounds(40, 90, 260, 15);

        xCheckBox4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox4.setText("Warrant of Levy");
        xCheckBox4.setCheckValue(1);
        xCheckBox4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox4.setName("entity.warrantoflevy");
        xCheckBox4.setUncheckValue(0);
        jPanel2.add(xCheckBox4);
        xCheckBox4.setBounds(40, 110, 260, 15);

        xCheckBox5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox5.setText("Notice of Publication and Auction Sale");
        xCheckBox5.setCheckValue(1);
        xCheckBox5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox5.setName("entity.noticeofpublication");
        xCheckBox5.setUncheckValue(0);
        jPanel2.add(xCheckBox5);
        xCheckBox5.setBounds(40, 130, 260, 15);

        xCheckBox6.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox6.setText("Certificate of Sale of Delinquent Real Property");
        xCheckBox6.setCheckValue(1);
        xCheckBox6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox6.setName("entity.certofsaleofproperty");
        xCheckBox6.setUncheckValue(0);
        jPanel2.add(xCheckBox6);
        xCheckBox6.setBounds(40, 150, 260, 15);

        xCheckBox7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox7.setText("Notice of Redemption");
        xCheckBox7.setCheckValue(1);
        xCheckBox7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox7.setName("entity.noticeofredemption");
        xCheckBox7.setUncheckValue(0);
        jPanel2.add(xCheckBox7);
        xCheckBox7.setBounds(40, 170, 260, 15);

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Check Available Demand Letters");
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 30, 330, 14);

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Other Settings");
        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 200, 330, 14);

        xCheckBox8.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox8.setText("Compute Advance Bill?");
        xCheckBox8.setCheckValue(1);
        xCheckBox8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox8.setName("entity.advancecomputation");
        xCheckBox8.setUncheckValue(0);
        jPanel2.add(xCheckBox8);
        xCheckBox8.setBounds(40, 220, 260, 15);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 540, 310);

        add(jPanel1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XCheckBox xCheckBox1;
    private com.rameses.rcp.control.XCheckBox xCheckBox2;
    private com.rameses.rcp.control.XCheckBox xCheckBox3;
    private com.rameses.rcp.control.XCheckBox xCheckBox4;
    private com.rameses.rcp.control.XCheckBox xCheckBox5;
    private com.rameses.rcp.control.XCheckBox xCheckBox6;
    private com.rameses.rcp.control.XCheckBox xCheckBox7;
    private com.rameses.rcp.control.XCheckBox xCheckBox8;
    // End of variables declaration//GEN-END:variables
    
}
