/*
 * RPTCompromiseInitPage.java
 *
 * Created on August 5, 2012, 10:44 AM
 */

package etracs2.rpt.compromise;

import com.rameses.rcp.ui.annotations.StyleSheet;
import java.math.BigDecimal;

/**
 *
 * @author  PRMF
 */
@StyleSheet("etracs2/rpt/compromise/RPTCompromisePage.style")
public class RPTCompromisePage extends javax.swing.JPanel {
    
    /** Creates new form RPTCompromiseInitPage */
    public RPTCompromisePage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xActionBar1 = new com.rameses.rcp.control.XActionBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xLabel18 = new com.rameses.rcp.control.XLabel();
        xLabel13 = new com.rameses.rcp.control.XLabel();
        xLabel14 = new com.rameses.rcp.control.XLabel();
        xLabel15 = new com.rameses.rcp.control.XLabel();
        xLabel16 = new com.rameses.rcp.control.XLabel();
        xLabel19 = new com.rameses.rcp.control.XLabel();
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xLabel9 = new com.rameses.rcp.control.XLabel();
        xLabel10 = new com.rameses.rcp.control.XLabel();
        xLabel11 = new com.rameses.rcp.control.XLabel();
        xLabel12 = new com.rameses.rcp.control.XLabel();
        xLabel17 = new com.rameses.rcp.control.XLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        formPanel6 = new com.rameses.rcp.util.FormPanel();
        xCheckBox1 = new com.rameses.rcp.control.XCheckBox();
        xCheckBox2 = new com.rameses.rcp.control.XCheckBox();
        xSeparator3 = new com.rameses.rcp.control.XSeparator();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        xSeparator1 = new com.rameses.rcp.control.XSeparator();
        xNumberField3 = new com.rameses.rcp.control.XNumberField();
        xNumberField4 = new com.rameses.rcp.control.XNumberField();
        xNumberField5 = new com.rameses.rcp.control.XNumberField();
        xSeparator2 = new com.rameses.rcp.control.XSeparator();
        xNumberField6 = new com.rameses.rcp.control.XNumberField();
        xDataTable3 = new com.rameses.rcp.control.XDataTable();
        jPanel3 = new javax.swing.JPanel();
        formPanel3 = new com.rameses.rcp.util.FormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xTextField6 = new com.rameses.rcp.control.XTextField();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        formPanel4 = new com.rameses.rcp.util.FormPanel();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xTextField7 = new com.rameses.rcp.control.XTextField();
        xTextField8 = new com.rameses.rcp.control.XTextField();
        xTextField9 = new com.rameses.rcp.control.XTextField();
        xDateField2 = new com.rameses.rcp.control.XDateField();
        xTextField10 = new com.rameses.rcp.control.XTextField();
        xComboBox4 = new com.rameses.rcp.control.XComboBox();
        xComboBox5 = new com.rameses.rcp.control.XComboBox();
        xComboBox6 = new com.rameses.rcp.control.XComboBox();
        jPanel6 = new javax.swing.JPanel();
        formPanel5 = new com.rameses.rcp.util.FormPanel();
        xTextField11 = new com.rameses.rcp.control.XTextField();
        xTextField12 = new com.rameses.rcp.control.XTextField();
        xDateField3 = new com.rameses.rcp.control.XDateField();
        xDataTable1 = new com.rameses.rcp.control.XDataTable();
        jPanel7 = new javax.swing.JPanel();
        formPanel7 = new com.rameses.rcp.util.FormPanel();
        xTextField13 = new com.rameses.rcp.control.XTextField();
        xDateField4 = new com.rameses.rcp.control.XDateField();
        xNumberField8 = new com.rameses.rcp.control.XNumberField();
        formPanel8 = new com.rameses.rcp.util.FormPanel();
        xTextField14 = new com.rameses.rcp.control.XTextField();
        xDateField5 = new com.rameses.rcp.control.XDateField();
        xNumberField7 = new com.rameses.rcp.control.XNumberField();
        xButton2 = new com.rameses.rcp.control.XButton();
        xButton3 = new com.rameses.rcp.control.XButton();
        jPanel5 = new javax.swing.JPanel();
        xDataTable2 = new com.rameses.rcp.control.XDataTable();
        jPanel8 = new javax.swing.JPanel();
        xDataTable4 = new com.rameses.rcp.control.XDataTable();
        xButton1 = new com.rameses.rcp.control.XButton();

        setLayout(new java.awt.BorderLayout());

        xActionBar1.setBorder(new com.rameses.rcp.control.border.XUnderlineBorder());
        xActionBar1.setName("formActions");
        add(xActionBar1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Compromise Agreement");
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(172, 25));
        jPanel1.add(jLabel1, java.awt.BorderLayout.NORTH);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Compromise Information");
        formPanel1.setBorder(xTitledBorder1);
        xLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel18.setForeground(new java.awt.Color(153, 0, 0));
        xLabel18.setCaption("State ");
        xLabel18.setCaptionWidth(120);
        xLabel18.setFont(new java.awt.Font("Arial", 1, 14));
        xLabel18.setName("entity.docstate");
        xLabel18.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel1.add(xLabel18);

        xLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel13.setCaption("Compromise No.");
        xLabel13.setCaptionWidth(120);
        xLabel13.setFont(new java.awt.Font("Arial", 1, 11));
        xLabel13.setName("entity.txnno");
        xLabel13.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel1.add(xLabel13);

        xLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel14.setCaption("Date Executed");
        xLabel14.setCaptionWidth(120);
        xLabel14.setFont(new java.awt.Font("Arial", 1, 11));
        xLabel14.setName("entity.txndate");
        xLabel14.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel1.add(xLabel14);

        xLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel15.setText("#{entity.info.startyear}, #{entity.info.startqtr}Q");
        xLabel15.setCaption("Start Year / Qtr");
        xLabel15.setCaptionWidth(120);
        xLabel15.setFont(new java.awt.Font("Arial", 1, 11));
        xLabel15.setName("entity.info.startyear");
        xLabel15.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel1.add(xLabel15);

        xLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel16.setText("#{entity.info.endyear}, #{entity.info.endqtr}Q");
        xLabel16.setCaption("End Year / Qtr");
        xLabel16.setCaptionWidth(120);
        xLabel16.setFont(new java.awt.Font("Arial", 1, 11));
        xLabel16.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel1.add(xLabel16);

        xLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel19.setCaption("Agreement End Date");
        xLabel19.setCaptionWidth(120);
        xLabel19.setFont(new java.awt.Font("Arial", 1, 11));
        xLabel19.setName("entity.info.enddate");
        xLabel19.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel1.add(xLabel19);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setTitle("Property Information");
        formPanel2.setBorder(xTitledBorder2);
        xLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel9.setCaption("TD No.");
        xLabel9.setCaptionWidth(120);
        xLabel9.setFont(new java.awt.Font("Arial", 1, 11));
        xLabel9.setName("entity.tdno");
        xLabel9.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel2.add(xLabel9);

        xLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel10.setCaption("Taxpayer Name");
        xLabel10.setCaptionWidth(120);
        xLabel10.setFont(new java.awt.Font("Arial", 1, 11));
        xLabel10.setName("entity.taxpayername");
        xLabel10.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel2.add(xLabel10);

        xLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel11.setCaption("PIN");
        xLabel11.setCaptionWidth(120);
        xLabel11.setFont(new java.awt.Font("Arial", 1, 11));
        xLabel11.setName("entity.fullpin");
        xLabel11.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel2.add(xLabel11);

        xLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel12.setCaption("Cadastral Lot No.");
        xLabel12.setCaptionWidth(120);
        xLabel12.setFont(new java.awt.Font("Arial", 1, 11));
        xLabel12.setName("entity.cadastrallotno");
        xLabel12.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel2.add(xLabel12);

        xLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel17.setCaption("Assessed Value");
        xLabel17.setCaptionWidth(120);
        xLabel17.setFont(new java.awt.Font("Arial", 1, 11));
        xLabel17.setName("entity.assessedvalue");
        xLabel17.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel2.add(xLabel17);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder3 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder3.setTitle("Details");
        formPanel6.setBorder(xTitledBorder3);
        xCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox1.setText(" Downpayment is required");
        xCheckBox1.setCellPadding(new java.awt.Insets(0, 5, 3, 0));
        xCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox1.setName("entity.info.downpaymentrequired");
        xCheckBox1.setReadonly(true);
        xCheckBox1.setShowCaption(false);
        formPanel6.add(xCheckBox1);

        xCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox2.setText(" Current Year payment is required");
        xCheckBox2.setCellPadding(new java.awt.Insets(0, 5, 3, 0));
        xCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox2.setName("entity.info.cypaymentrequired");
        xCheckBox2.setReadonly(true);
        xCheckBox2.setShowCaption(false);
        formPanel6.add(xCheckBox2);

        xSeparator3.setPreferredSize(new java.awt.Dimension(0, 20));
        org.jdesktop.layout.GroupLayout xSeparator3Layout = new org.jdesktop.layout.GroupLayout(xSeparator3);
        xSeparator3.setLayout(xSeparator3Layout);
        xSeparator3Layout.setHorizontalGroup(
            xSeparator3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 226, Short.MAX_VALUE)
        );
        xSeparator3Layout.setVerticalGroup(
            xSeparator3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 20, Short.MAX_VALUE)
        );
        formPanel6.add(xSeparator3);

        xNumberField1.setCaption("Term");
        xNumberField1.setCaptionWidth(120);
        xNumberField1.setEnabled(false);
        xNumberField1.setName("entity.info.term");
        xNumberField1.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel6.add(xNumberField1);

        xNumberField2.setCaption("No. of Installments");
        xNumberField2.setCaptionWidth(120);
        xNumberField2.setEnabled(false);
        xNumberField2.setName("entity.info.numofinstallment");
        xNumberField2.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel6.add(xNumberField2);

        xSeparator1.setPreferredSize(new java.awt.Dimension(0, 20));
        org.jdesktop.layout.GroupLayout xSeparator1Layout = new org.jdesktop.layout.GroupLayout(xSeparator1);
        xSeparator1.setLayout(xSeparator1Layout);
        xSeparator1Layout.setHorizontalGroup(
            xSeparator1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 226, Short.MAX_VALUE)
        );
        xSeparator1Layout.setVerticalGroup(
            xSeparator1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 20, Short.MAX_VALUE)
        );
        formPanel6.add(xSeparator1);

        xNumberField3.setCaption("Delinquent Amount");
        xNumberField3.setCaptionWidth(120);
        xNumberField3.setEnabled(false);
        xNumberField3.setName("entity.info.amount");
        xNumberField3.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel6.add(xNumberField3);

        xNumberField4.setCaption("Downpayment Rate");
        xNumberField4.setCaptionWidth(120);
        xNumberField4.setEnabled(false);
        xNumberField4.setFieldType(BigDecimal.class);
        xNumberField4.setName("entity.info.downpaymentrate");
        xNumberField4.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel6.add(xNumberField4);

        xNumberField5.setCaption("Downpayment");
        xNumberField5.setCaptionWidth(120);
        xNumberField5.setEnabled(false);
        xNumberField5.setName("entity.info.downpayment");
        xNumberField5.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel6.add(xNumberField5);

        xSeparator2.setPreferredSize(new java.awt.Dimension(0, 20));
        org.jdesktop.layout.GroupLayout xSeparator2Layout = new org.jdesktop.layout.GroupLayout(xSeparator2);
        xSeparator2.setLayout(xSeparator2Layout);
        xSeparator2Layout.setHorizontalGroup(
            xSeparator2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 226, Short.MAX_VALUE)
        );
        xSeparator2Layout.setVerticalGroup(
            xSeparator2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 20, Short.MAX_VALUE)
        );
        formPanel6.add(xSeparator2);

        xNumberField6.setCaption("Amount for Installment");
        xNumberField6.setCaptionWidth(120);
        xNumberField6.setEnabled(false);
        xNumberField6.setFont(new java.awt.Font("Arial", 1, 12));
        xNumberField6.setName("entity.info.amtforinstallment");
        xNumberField6.setPreferredSize(new java.awt.Dimension(0, 21));
        formPanel6.add(xNumberField6);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder4 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder4.setTitle("Schedules");
        xDataTable3.setBorder(xTitledBorder4);
        xDataTable3.setHandler("installmentListHandler");
        xDataTable3.setShowRowHeader(true);

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 240, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(xDataTable3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, xDataTable3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, formPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jTabbedPane1.addTab("Installment Information", jPanel4);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder5 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder5.setTitle("First Party");
        formPanel3.setBorder(xTitledBorder5);
        xTextField1.setCaption("Name");
        xTextField1.setName("entity.info.firstpartyname");
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField1.setRequired(true);
        formPanel3.add(xTextField1);

        xTextField2.setCaption("Job Title");
        xTextField2.setName("entity.info.firstpartytitle");
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField2.setRequired(true);
        formPanel3.add(xTextField2);

        xTextField3.setCaption("Address");
        xTextField3.setName("entity.info.firstpartyaddress");
        xTextField3.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField3.setRequired(true);
        formPanel3.add(xTextField3);

        xTextField4.setCaption("CTC No.");
        xTextField4.setName("entity.info.firstpartyctcno");
        xTextField4.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField4.setRequired(true);
        formPanel3.add(xTextField4);

        xDateField1.setCaption("Issue Date");
        xDateField1.setName("entity.info.firstpartyctcdate");
        xDateField1.setPreferredSize(new java.awt.Dimension(0, 19));
        xDateField1.setRequired(true);
        formPanel3.add(xDateField1);

        xTextField6.setCaption("Issued at");
        xTextField6.setName("entity.info.firstpartyctcissued");
        xTextField6.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField6.setRequired(true);
        formPanel3.add(xTextField6);

        xComboBox1.setCaption("Nationality");
        xComboBox1.setItems("nationalityList");
        xComboBox1.setName("entity.info.firstpartynationality");
        xComboBox1.setPreferredSize(new java.awt.Dimension(0, 22));
        xComboBox1.setRequired(true);
        formPanel3.add(xComboBox1);

        xComboBox2.setCaption("Civil Status");
        xComboBox2.setItems("civilStatusList");
        xComboBox2.setName("entity.info.firstpartystatus");
        xComboBox2.setPreferredSize(new java.awt.Dimension(0, 22));
        xComboBox2.setRequired(true);
        formPanel3.add(xComboBox2);

        xComboBox3.setCaption("Gender");
        xComboBox3.setItems("genderList");
        xComboBox3.setName("entity.info.firstpartygender");
        xComboBox3.setPreferredSize(new java.awt.Dimension(0, 22));
        xComboBox3.setRequired(true);
        formPanel3.add(xComboBox3);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder6 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder6.setTitle("Second Party");
        formPanel4.setBorder(xTitledBorder6);
        xTextField5.setCaption("Representative");
        xTextField5.setCaptionWidth(110);
        xTextField5.setName("entity.info.secondpartyrepresentative");
        xTextField5.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField5.setRequired(true);
        formPanel4.add(xTextField5);

        xTextField7.setCaption("Name");
        xTextField7.setCaptionWidth(110);
        xTextField7.setName("entity.info.secondpartyname");
        xTextField7.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField7.setRequired(true);
        formPanel4.add(xTextField7);

        xTextField8.setCaption("Address");
        xTextField8.setCaptionWidth(110);
        xTextField8.setName("entity.info.secondpartyaddress");
        xTextField8.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField8.setRequired(true);
        formPanel4.add(xTextField8);

        xTextField9.setCaption("CTC No.");
        xTextField9.setCaptionWidth(110);
        xTextField9.setName("entity.info.secondpartyctcno");
        xTextField9.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField9.setRequired(true);
        formPanel4.add(xTextField9);

        xDateField2.setCaption("Issue Date");
        xDateField2.setCaptionWidth(110);
        xDateField2.setName("entity.info.secondpartyctcdate");
        xDateField2.setPreferredSize(new java.awt.Dimension(0, 19));
        xDateField2.setRequired(true);
        formPanel4.add(xDateField2);

        xTextField10.setCaption("Issued at");
        xTextField10.setCaptionWidth(110);
        xTextField10.setName("entity.info.secondpartyctcissued");
        xTextField10.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField10.setRequired(true);
        formPanel4.add(xTextField10);

        xComboBox4.setCaption("Nationality");
        xComboBox4.setCaptionWidth(110);
        xComboBox4.setItems("nationalityList");
        xComboBox4.setName("entity.info.secondpartynationality");
        xComboBox4.setPreferredSize(new java.awt.Dimension(0, 22));
        xComboBox4.setRequired(true);
        formPanel4.add(xComboBox4);

        xComboBox5.setCaption("Civil Status");
        xComboBox5.setCaptionWidth(110);
        xComboBox5.setItems("civilStatusList");
        xComboBox5.setName("entity.info.secondpartystatus");
        xComboBox5.setPreferredSize(new java.awt.Dimension(0, 22));
        xComboBox5.setRequired(true);
        formPanel4.add(xComboBox5);

        xComboBox6.setCaption("Gender");
        xComboBox6.setCaptionWidth(110);
        xComboBox6.setItems("genderList");
        xComboBox6.setName("entity.info.secondpartygender");
        xComboBox6.setPreferredSize(new java.awt.Dimension(0, 22));
        xComboBox6.setRequired(true);
        formPanel4.add(xComboBox6);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 395, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(formPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 405, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(formPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 246, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(formPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addContainerGap())
        );
        jTabbedPane1.addTab("Agreement Information", jPanel3);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder7 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder7.setTitle("Notarized By Detail");
        formPanel5.setBorder(xTitledBorder7);
        xTextField11.setCaption("Notarized By");
        xTextField11.setCaptionWidth(90);
        xTextField11.setName("entity.info.notarizedby");
        xTextField11.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel5.add(xTextField11);

        xTextField12.setCaption("Title ");
        xTextField12.setCaptionWidth(90);
        xTextField12.setName("entity.info.notarizedbytitle");
        xTextField12.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel5.add(xTextField12);

        xDateField3.setCaption("Date");
        xDateField3.setCaptionWidth(90);
        xDateField3.setName("entity.info.notarizeddate");
        xDateField3.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel5.add(xDateField3);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder8 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder8.setTitle("List of Witnesses");
        xDataTable1.setBorder(xTitledBorder8);
        xDataTable1.setHandler("witnessListHandler");
        xDataTable1.setName("selectedWitness");
        xDataTable1.setShowRowHeader(true);

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 404, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(xDataTable1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, formPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, xDataTable1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addContainerGap())
        );
        jTabbedPane1.addTab("Notary Public and Witnesses", jPanel6);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder9 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder9.setTitle("Downpayment Information");
        formPanel7.setBorder(xTitledBorder9);
        xTextField13.setCaption("O.R. No.");
        xTextField13.setName("entity.info.downpaymentorno");
        xTextField13.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel7.add(xTextField13);

        xDateField4.setCaption("O.R. Date");
        xDateField4.setName("entity.info.downpaymentordate");
        xDateField4.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel7.add(xDateField4);

        xNumberField8.setCaption("O.R. Amount");
        xNumberField8.setFieldType(BigDecimal.class);
        xNumberField8.setName("entity.info.downpayment");
        xNumberField8.setPreferredSize(new java.awt.Dimension(120, 19));
        xNumberField8.setReadonly(true);
        formPanel7.add(xNumberField8);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder10 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder10.setTitle("Current Year Payment Information");
        formPanel8.setBorder(xTitledBorder10);
        xTextField14.setCaption("O.R. No.");
        xTextField14.setName("entity.info.cypaymentorno");
        xTextField14.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel8.add(xTextField14);

        xDateField5.setCaption("O.R. Date");
        xDateField5.setName("entity.info.cypaymentordate");
        xDateField5.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel8.add(xDateField5);

        xNumberField7.setCaption("O.R. Amount");
        xNumberField7.setFieldType(BigDecimal.class);
        xNumberField7.setName("entity.info.cypaymentoramount");
        xNumberField7.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel8.add(xNumberField7);

        xButton2.setText("Capture Downpayment");
        xButton2.setName("captureDownpayment");

        xButton3.setText("Capture Current Year Payment");
        xButton3.setName("captureCYPayment");

        org.jdesktop.layout.GroupLayout jPanel7Layout = new org.jdesktop.layout.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(formPanel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 274, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(xButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(xButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(formPanel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 279, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(298, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(formPanel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 164, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(formPanel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 164, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(xButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(xButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jTabbedPane1.addTab("Required Payments", jPanel7);

        xDataTable2.setHandler("delinquentListHandler");

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(xDataTable2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(xDataTable2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );
        jTabbedPane1.addTab("Delinquent Data", jPanel5);

        xDataTable4.setHandler("creditListHandler");
        xDataTable4.setShowRowHeader(true);

        xButton1.setMnemonic('m');
        xButton1.setText("Capture Payment");
        xButton1.setName("capturePayment");

        org.jdesktop.layout.GroupLayout jPanel8Layout = new org.jdesktop.layout.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(xDataTable4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
                    .add(xButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .add(xDataTable4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(xButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jTabbedPane1.addTab("Credits", jPanel8);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 374, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(formPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(formPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(formPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.util.FormPanel formPanel2;
    private com.rameses.rcp.util.FormPanel formPanel3;
    private com.rameses.rcp.util.FormPanel formPanel4;
    private com.rameses.rcp.util.FormPanel formPanel5;
    private com.rameses.rcp.util.FormPanel formPanel6;
    private com.rameses.rcp.util.FormPanel formPanel7;
    private com.rameses.rcp.util.FormPanel formPanel8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XButton xButton3;
    private com.rameses.rcp.control.XCheckBox xCheckBox1;
    private com.rameses.rcp.control.XCheckBox xCheckBox2;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XComboBox xComboBox4;
    private com.rameses.rcp.control.XComboBox xComboBox5;
    private com.rameses.rcp.control.XComboBox xComboBox6;
    private com.rameses.rcp.control.XDataTable xDataTable1;
    private com.rameses.rcp.control.XDataTable xDataTable2;
    private com.rameses.rcp.control.XDataTable xDataTable3;
    private com.rameses.rcp.control.XDataTable xDataTable4;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XDateField xDateField3;
    private com.rameses.rcp.control.XDateField xDateField4;
    private com.rameses.rcp.control.XDateField xDateField5;
    private com.rameses.rcp.control.XLabel xLabel10;
    private com.rameses.rcp.control.XLabel xLabel11;
    private com.rameses.rcp.control.XLabel xLabel12;
    private com.rameses.rcp.control.XLabel xLabel13;
    private com.rameses.rcp.control.XLabel xLabel14;
    private com.rameses.rcp.control.XLabel xLabel15;
    private com.rameses.rcp.control.XLabel xLabel16;
    private com.rameses.rcp.control.XLabel xLabel17;
    private com.rameses.rcp.control.XLabel xLabel18;
    private com.rameses.rcp.control.XLabel xLabel19;
    private com.rameses.rcp.control.XLabel xLabel9;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    private com.rameses.rcp.control.XNumberField xNumberField3;
    private com.rameses.rcp.control.XNumberField xNumberField4;
    private com.rameses.rcp.control.XNumberField xNumberField5;
    private com.rameses.rcp.control.XNumberField xNumberField6;
    private com.rameses.rcp.control.XNumberField xNumberField7;
    private com.rameses.rcp.control.XNumberField xNumberField8;
    private com.rameses.rcp.control.XSeparator xSeparator1;
    private com.rameses.rcp.control.XSeparator xSeparator2;
    private com.rameses.rcp.control.XSeparator xSeparator3;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField10;
    private com.rameses.rcp.control.XTextField xTextField11;
    private com.rameses.rcp.control.XTextField xTextField12;
    private com.rameses.rcp.control.XTextField xTextField13;
    private com.rameses.rcp.control.XTextField xTextField14;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    private com.rameses.rcp.control.XTextField xTextField6;
    private com.rameses.rcp.control.XTextField xTextField7;
    private com.rameses.rcp.control.XTextField xTextField8;
    private com.rameses.rcp.control.XTextField xTextField9;
    // End of variables declaration//GEN-END:variables
    
}
