/*
 * RPUpdatePage.java
 *
 * Created on May 30, 2012, 4:47 PM
 */

package etracs2.rpt.update;

import com.rameses.rcp.ui.annotations.StyleSheet;

/**
 *
 * @author  JAYROME VERGARA
 */

@StyleSheet
public class FAASTitleUpdatePage extends javax.swing.JPanel {
    
    /** Creates new form RPUpdatePage */
    public FAASTitleUpdatePage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xActionBar1 = new com.rameses.rcp.control.XActionBar();
        jPanel1 = new javax.swing.JPanel();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        jPanel2 = new javax.swing.JPanel();
        formPanel3 = new com.rameses.rcp.util.FormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField13 = new com.rameses.rcp.control.XTextField();
        xTextField12 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        formPanel4 = new com.rameses.rcp.util.FormPanel();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xTextField6 = new com.rameses.rcp.control.XTextField();
        xTextField8 = new com.rameses.rcp.control.XTextField();
        xDateField2 = new com.rameses.rcp.control.XDateField();
        formPanel5 = new com.rameses.rcp.util.FormPanel();
        xTextField7 = new com.rameses.rcp.control.XTextField();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        xNumberField3 = new com.rameses.rcp.control.XNumberField();
        jPanel3 = new javax.swing.JPanel();
        formPanel6 = new com.rameses.rcp.util.FormPanel();
        xTextField11 = new com.rameses.rcp.control.XTextField();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();

        xActionBar1.setBorder(new com.rameses.rcp.control.border.XUnderlineBorder());
        xActionBar1.setName("formActions");
        xActionBar1.setPreferredSize(new java.awt.Dimension(61, 32));

        formPanel1.setCaptionFont(new java.awt.Font("Arial", 1, 14));
        formPanel1.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        formPanel1.setCaptionWidth(75);
        formPanel1.setRequired(true);
        xLookupField1.setCaption("TD No.");
        xLookupField1.setExpression("#{tdno}");
        xLookupField1.setFont(new java.awt.Font("Arial", 1, 14));
        xLookupField1.setHandler("faasLookupHandler");
        xLookupField1.setIndex(-1);
        xLookupField1.setName("faasinfo");
        xLookupField1.setPreferredSize(new java.awt.Dimension(0, 22));
        xLookupField1.setRequired(true);
        xLookupField1.setTranserFocusOnSelect(false);
        formPanel1.add(xLookupField1);

        formPanel2.setCaptionFont(new java.awt.Font("Arial", 1, 14));
        formPanel2.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        formPanel2.setCaptionWidth(60);
        xLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        xLabel1.setCaption("State");
        xLabel1.setFont(new java.awt.Font("Arial", 1, 14));
        xLabel1.setName("entity.state");
        xLabel1.setPreferredSize(new java.awt.Dimension(0, 22));
        formPanel2.add(xLabel1);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 318, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 82, Short.MAX_VALUE)
                .add(formPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 224, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(formPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Tax Declaration Information");
        jPanel2.setBorder(xTitledBorder1);

        formPanel3.setCaptionWidth(100);
        xTextField1.setCaption("Taxpayer");
        xTextField1.setEnabled(false);
        xTextField1.setName("entity.faas.info.taxpayername");
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel3.add(xTextField1);

        xTextField13.setCaption("Address");
        xTextField13.setEnabled(false);
        xTextField13.setName("entity.faas.info.taxpayeraddress");
        xTextField13.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel3.add(xTextField13);

        xTextField12.setCaption("Declared Owner");
        xTextField12.setEnabled(false);
        xTextField12.setName("entity.faas.info.ownername");
        xTextField12.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel3.add(xTextField12);

        xTextField2.setCaption("Address");
        xTextField2.setEnabled(false);
        xTextField2.setName("entity.faas.info.owneraddress");
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel3.add(xTextField2);

        formPanel4.setCaptionWidth(100);
        xTextField3.setCaption("PIN");
        xTextField3.setEnabled(false);
        xTextField3.setName("entity.faas.rp.pin");
        xTextField3.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel4.add(xTextField3);

        xTextField4.setCaption("Cadastral Lot");
        xTextField4.setEnabled(false);
        xTextField4.setName("entity.faas.rp.cadastrallotno");
        xTextField4.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel4.add(xTextField4);

        xTextField5.setCaption("Location");
        xTextField5.setEnabled(false);
        xTextField5.setName("entity.faas.rp.location");
        xTextField5.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel4.add(xTextField5);

        xTextField6.setCaption("Survey No.");
        xTextField6.setEnabled(false);
        xTextField6.setName("entity.faas.rp.surveyno");
        xTextField6.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel4.add(xTextField6);

        xTextField8.setCaption("Title No.");
        xTextField8.setEnabled(false);
        xTextField8.setName("entity.faas.info.titleno");
        xTextField8.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel4.add(xTextField8);

        xDateField2.setCaption("Title Date");
        xDateField2.setEnabled(false);
        xDateField2.setName("entity.faas.info.titledate");
        xDateField2.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel4.add(xDateField2);

        formPanel5.setCaptionWidth(130);
        xTextField7.setCaption("Classification");
        xTextField7.setEnabled(false);
        xTextField7.setName("entity.faas.rpu.classcode");
        xTextField7.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel5.add(xTextField7);

        xNumberField1.setCaption("Market Value");
        xNumberField1.setEnabled(false);
        xNumberField1.setFieldType(java.math.BigDecimal.class);
        xNumberField1.setName("entity.faas.rpu.totalbmv");
        xNumberField1.setPattern("#,##0.00");
        xNumberField1.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel5.add(xNumberField1);

        xNumberField2.setCaption("Adjusted Market Value");
        xNumberField2.setEnabled(false);
        xNumberField2.setFieldType(java.math.BigDecimal.class);
        xNumberField2.setName("entity.faas.rpu.totalmv");
        xNumberField2.setPattern("#,##0.00");
        xNumberField2.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel5.add(xNumberField2);

        xNumberField3.setCaption("Assessed Value");
        xNumberField3.setEnabled(false);
        xNumberField3.setFieldType(java.math.BigDecimal.class);
        xNumberField3.setName("entity.faas.rpu.totalav");
        xNumberField3.setPattern("#,##0.00");
        xNumberField3.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel5.add(xNumberField3);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(formPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 317, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(formPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 277, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(formPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(formPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(formPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(formPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setTitle("New Title Information");
        jPanel3.setBorder(xTitledBorder2);

        formPanel6.setCaptionWidth(100);
        xTextField11.setCaption("Title No.");
        xTextField11.setName("entity.titleno");
        xTextField11.setPreferredSize(new java.awt.Dimension(200, 19));
        xTextField11.setRequired(true);
        formPanel6.add(xTextField11);

        xDateField1.setCaption("Title Date");
        xDateField1.setName("entity.titledate");
        xDateField1.setPreferredSize(new java.awt.Dimension(120, 19));
        xDateField1.setRequired(true);
        formPanel6.add(xDateField1);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 76));
        xTextArea1.setColumns(20);
        xTextArea1.setRows(5);
        xTextArea1.setCaption("Remarks");
        xTextArea1.setName("entity.remarks");
        xTextArea1.setRequired(true);
        xTextArea1.setTrimSpaceOption(com.rameses.rcp.constant.TrimSpaceOption.NORMAL);
        jScrollPane1.setViewportView(xTextArea1);

        formPanel6.add(jScrollPane1);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(xActionBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(134, 134, 134))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(xActionBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.util.FormPanel formPanel2;
    private com.rameses.rcp.util.FormPanel formPanel3;
    private com.rameses.rcp.util.FormPanel formPanel4;
    private com.rameses.rcp.util.FormPanel formPanel5;
    private com.rameses.rcp.util.FormPanel formPanel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    private com.rameses.rcp.control.XNumberField xNumberField3;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField11;
    private com.rameses.rcp.control.XTextField xTextField12;
    private com.rameses.rcp.control.XTextField xTextField13;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    private com.rameses.rcp.control.XTextField xTextField6;
    private com.rameses.rcp.control.XTextField xTextField7;
    private com.rameses.rcp.control.XTextField xTextField8;
    // End of variables declaration//GEN-END:variables
    
}
