/*
 * RPUpdatePage.java
 *
 * Created on May 30, 2012, 4:47 PM
 */

package etracs2.rpt.update;

import com.rameses.rcp.ui.annotations.StyleSheet;

/**
 *
 * @author  JAYROME VERGARA
 */

@StyleSheet
public class RPUpdatePage extends javax.swing.JPanel {
    
    /** Creates new form RPUpdatePage */
    public RPUpdatePage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        xTextField10 = new com.rameses.rcp.control.XTextField();
        xTextField11 = new com.rameses.rcp.control.XTextField();
        xTextField12 = new com.rameses.rcp.control.XTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        xTextField13 = new com.rameses.rcp.control.XTextField();
        xTextField14 = new com.rameses.rcp.control.XTextField();
        xTextField15 = new com.rameses.rcp.control.XTextField();
        xTextField17 = new com.rameses.rcp.control.XTextField();
        xTextField16 = new com.rameses.rcp.control.XTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        xTextField18 = new com.rameses.rcp.control.XTextField();
        xTextField19 = new com.rameses.rcp.control.XTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        xActionBar1 = new com.rameses.rcp.control.XActionBar();
        jPanel1 = new javax.swing.JPanel();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        xTextField20 = new com.rameses.rcp.control.XTextField();
        xTextField21 = new com.rameses.rcp.control.XTextField();
        xTextField22 = new com.rameses.rcp.control.XTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        xTextField23 = new com.rameses.rcp.control.XTextField();
        xTextField24 = new com.rameses.rcp.control.XTextField();
        xTextField25 = new com.rameses.rcp.control.XTextField();
        xTextField26 = new com.rameses.rcp.control.XTextField();
        xTextField27 = new com.rameses.rcp.control.XTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        xTextField28 = new com.rameses.rcp.control.XTextField();
        xTextField29 = new com.rameses.rcp.control.XTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();

        jPanel8.setLayout(null);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Original Real Property Information");
        jPanel8.setBorder(xTitledBorder1);
        jPanel10.setLayout(null);

        jPanel10.setOpaque(false);
        jLabel32.setText("Block No. :");
        jLabel32.setPreferredSize(new java.awt.Dimension(34, 19));
        jPanel10.add(jLabel32);
        jLabel32.setBounds(2, 24, 70, 19);

        jLabel33.setText("Cadastral * :");
        jLabel33.setPreferredSize(new java.awt.Dimension(34, 19));
        jPanel10.add(jLabel33);
        jLabel33.setBounds(2, 4, 70, 19);

        jLabel38.setText("Survey No. :");
        jLabel38.setPreferredSize(new java.awt.Dimension(34, 19));
        jPanel10.add(jLabel38);
        jLabel38.setBounds(132, 24, 66, 19);

        xTextField10.setCaption("Cadastral ");
        xTextField10.setEnabled(false);
        xTextField10.setName("entity.prevcadastrallotno");
        jPanel10.add(xTextField10);
        xTextField10.setBounds(72, 4, 254, 19);

        xTextField11.setEnabled(false);
        xTextField11.setName("entity.prevblockno");
        jPanel10.add(xTextField11);
        xTextField11.setBounds(72, 23, 58, 19);

        xTextField12.setEnabled(false);
        xTextField12.setName("entity.prevsurveyno");
        jPanel10.add(xTextField12);
        xTextField12.setBounds(198, 23, 128, 19);

        jPanel8.add(jPanel10);
        jPanel10.setBounds(6, 22, 330, 64);

        jPanel11.setLayout(null);

        jPanel11.setOpaque(false);
        jLabel35.setText("Purok/Zone :");
        jLabel35.setPreferredSize(new java.awt.Dimension(34, 19));
        jPanel11.add(jLabel35);
        jLabel35.setBounds(4, 42, 70, 19);

        jLabel36.setText("Street :");
        jLabel36.setPreferredSize(new java.awt.Dimension(34, 19));
        jPanel11.add(jLabel36);
        jLabel36.setBounds(4, 23, 70, 19);

        jLabel37.setText("House No. :");
        jLabel37.setPreferredSize(new java.awt.Dimension(34, 19));
        jPanel11.add(jLabel37);
        jLabel37.setBounds(4, 4, 70, 19);

        xTextField13.setEnabled(false);
        xTextField13.setName("entity.prevhouseno");
        jPanel11.add(xTextField13);
        xTextField13.setBounds(72, 4, 128, 19);

        xTextField14.setEnabled(false);
        xTextField14.setName("entity.prevstreet");
        jPanel11.add(xTextField14);
        xTextField14.setBounds(72, 23, 128, 19);

        xTextField15.setEnabled(false);
        xTextField15.setName("entity.prevpurok");
        jPanel11.add(xTextField15);
        xTextField15.setBounds(72, 42, 128, 19);

        jPanel8.add(jPanel11);
        jPanel11.setBounds(336, 22, 206, 64);

        xTextField17.setCaption("South Boundary");
        xTextField17.setEnabled(false);
        xTextField17.setName("entity.preveast");
        jPanel8.add(xTextField17);
        xTextField17.setBounds(78, 108, 458, 19);

        xTextField16.setCaption("North Boundary");
        xTextField16.setEnabled(false);
        xTextField16.setName("entity.prevnorth");
        jPanel8.add(xTextField16);
        xTextField16.setBounds(78, 90, 458, 19);

        jLabel39.setText("North * :");
        jLabel39.setPreferredSize(new java.awt.Dimension(34, 19));
        jPanel8.add(jLabel39);
        jLabel39.setBounds(8, 90, 70, 19);

        jLabel40.setText("East * :");
        jLabel40.setPreferredSize(new java.awt.Dimension(34, 19));
        jPanel8.add(jLabel40);
        jLabel40.setBounds(8, 108, 70, 19);

        xTextField18.setCaption("West Boundary");
        xTextField18.setEnabled(false);
        xTextField18.setName("entity.prevwest");
        jPanel8.add(xTextField18);
        xTextField18.setBounds(78, 144, 458, 19);

        xTextField19.setCaption("East Boundary");
        xTextField19.setEnabled(false);
        xTextField19.setName("entity.prevsouth");
        jPanel8.add(xTextField19);
        xTextField19.setBounds(78, 126, 458, 19);

        jLabel41.setText("South * :");
        jLabel41.setPreferredSize(new java.awt.Dimension(34, 19));
        jPanel8.add(jLabel41);
        jLabel41.setBounds(8, 126, 70, 19);

        jLabel42.setText("West *  :");
        jLabel42.setPreferredSize(new java.awt.Dimension(34, 19));
        jPanel8.add(jLabel42);
        jLabel42.setBounds(8, 144, 70, 19);

        xActionBar1.setBorder(new com.rameses.rcp.control.border.XUnderlineBorder());
        xActionBar1.setName("formActions");
        xActionBar1.setPreferredSize(new java.awt.Dimension(61, 32));

        formPanel1.setCaptionFont(new java.awt.Font("Arial", 1, 14));
        formPanel1.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        formPanel1.setCaptionWidth(50);
        formPanel1.setRequired(true);
        xLookupField1.setCaption("PIN");
        xLookupField1.setExpression("#{pin}");
        xLookupField1.setFont(new java.awt.Font("Arial", 1, 14));
        xLookupField1.setHandler("rplookupHandler");
        xLookupField1.setIndex(-1);
        xLookupField1.setName("rpinfo");
        xLookupField1.setPreferredSize(new java.awt.Dimension(0, 22));
        xLookupField1.setTranserFocusOnSelect(false);
        formPanel1.add(xLookupField1);

        formPanel2.setCaptionFont(new java.awt.Font("Arial", 1, 14));
        formPanel2.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        formPanel2.setCaptionWidth(60);
        xLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        xLabel1.setCaption("State");
        xLabel1.setFont(new java.awt.Font("Arial", 1, 14));
        xLabel1.setName("entity.state");
        xLabel1.setPreferredSize(new java.awt.Dimension(0, 22));
        formPanel2.add(xLabel1);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 318, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 27, Short.MAX_VALUE)
                .add(formPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 224, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(formPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        jPanel9.setLayout(null);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setTitle("New Real Property Information");
        jPanel9.setBorder(xTitledBorder2);
        jPanel12.setLayout(null);

        jPanel12.setOpaque(false);
        jLabel34.setText("Block No. :");
        jLabel34.setPreferredSize(new java.awt.Dimension(34, 19));
        jPanel12.add(jLabel34);
        jLabel34.setBounds(2, 24, 70, 19);

        jLabel43.setText("Cadastral * :");
        jLabel43.setPreferredSize(new java.awt.Dimension(34, 19));
        jPanel12.add(jLabel43);
        jLabel43.setBounds(2, 4, 70, 19);

        jLabel44.setText("Survey No. :");
        jLabel44.setPreferredSize(new java.awt.Dimension(34, 19));
        jPanel12.add(jLabel44);
        jLabel44.setBounds(132, 24, 66, 19);

        xTextField20.setCaption("New Cadastral");
        xTextField20.setName("entity.cadastrallotno");
        xTextField20.setRequired(true);
        jPanel12.add(xTextField20);
        xTextField20.setBounds(72, 4, 254, 19);

        xTextField21.setName("entity.blockno");
        jPanel12.add(xTextField21);
        xTextField21.setBounds(72, 23, 58, 19);

        xTextField22.setName("entity.surveyno");
        jPanel12.add(xTextField22);
        xTextField22.setBounds(198, 23, 128, 19);

        jPanel9.add(jPanel12);
        jPanel12.setBounds(6, 22, 330, 64);

        jPanel13.setLayout(null);

        jPanel13.setOpaque(false);
        jLabel45.setText("Purok/Zone :");
        jLabel45.setPreferredSize(new java.awt.Dimension(34, 19));
        jPanel13.add(jLabel45);
        jLabel45.setBounds(4, 42, 70, 19);

        jLabel46.setText("Street :");
        jLabel46.setPreferredSize(new java.awt.Dimension(34, 19));
        jPanel13.add(jLabel46);
        jLabel46.setBounds(4, 23, 70, 19);

        jLabel47.setText("House No. :");
        jLabel47.setPreferredSize(new java.awt.Dimension(34, 19));
        jPanel13.add(jLabel47);
        jLabel47.setBounds(4, 4, 70, 19);

        xTextField23.setName("entity.houseno");
        jPanel13.add(xTextField23);
        xTextField23.setBounds(72, 4, 128, 19);

        xTextField24.setName("entity.street");
        jPanel13.add(xTextField24);
        xTextField24.setBounds(72, 23, 128, 19);

        xTextField25.setName("entity.purok");
        jPanel13.add(xTextField25);
        xTextField25.setBounds(72, 42, 128, 19);

        jPanel9.add(jPanel13);
        jPanel13.setBounds(336, 22, 206, 64);

        xTextField26.setCaption("New South Boundary");
        xTextField26.setName("entity.east");
        xTextField26.setRequired(true);
        jPanel9.add(xTextField26);
        xTextField26.setBounds(78, 108, 458, 19);

        xTextField27.setCaption("New North Boundary");
        xTextField27.setName("entity.north");
        xTextField27.setRequired(true);
        jPanel9.add(xTextField27);
        xTextField27.setBounds(78, 90, 458, 19);

        jLabel48.setText("North * :");
        jLabel48.setPreferredSize(new java.awt.Dimension(34, 19));
        jPanel9.add(jLabel48);
        jLabel48.setBounds(8, 90, 70, 19);

        jLabel49.setText("East * :");
        jLabel49.setPreferredSize(new java.awt.Dimension(34, 19));
        jPanel9.add(jLabel49);
        jLabel49.setBounds(8, 108, 70, 19);

        xTextField28.setCaption("New West Boundary");
        xTextField28.setName("entity.west");
        xTextField28.setRequired(true);
        jPanel9.add(xTextField28);
        xTextField28.setBounds(78, 144, 458, 19);

        xTextField29.setCaption("New East Boundary");
        xTextField29.setName("entity.south");
        xTextField29.setRequired(true);
        jPanel9.add(xTextField29);
        xTextField29.setBounds(78, 126, 458, 19);

        jLabel50.setText("South * :");
        jLabel50.setPreferredSize(new java.awt.Dimension(34, 19));
        jPanel9.add(jLabel50);
        jLabel50.setBounds(8, 126, 70, 19);

        jLabel51.setText("West *  :");
        jLabel51.setPreferredSize(new java.awt.Dimension(34, 19));
        jPanel9.add(jLabel51);
        jLabel51.setBounds(8, 144, 70, 19);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(xActionBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 569, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE))
                .add(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(xActionBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 185, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 185, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.util.FormPanel formPanel2;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XTextField xTextField10;
    private com.rameses.rcp.control.XTextField xTextField11;
    private com.rameses.rcp.control.XTextField xTextField12;
    private com.rameses.rcp.control.XTextField xTextField13;
    private com.rameses.rcp.control.XTextField xTextField14;
    private com.rameses.rcp.control.XTextField xTextField15;
    private com.rameses.rcp.control.XTextField xTextField16;
    private com.rameses.rcp.control.XTextField xTextField17;
    private com.rameses.rcp.control.XTextField xTextField18;
    private com.rameses.rcp.control.XTextField xTextField19;
    private com.rameses.rcp.control.XTextField xTextField20;
    private com.rameses.rcp.control.XTextField xTextField21;
    private com.rameses.rcp.control.XTextField xTextField22;
    private com.rameses.rcp.control.XTextField xTextField23;
    private com.rameses.rcp.control.XTextField xTextField24;
    private com.rameses.rcp.control.XTextField xTextField25;
    private com.rameses.rcp.control.XTextField xTextField26;
    private com.rameses.rcp.control.XTextField xTextField27;
    private com.rameses.rcp.control.XTextField xTextField28;
    private com.rameses.rcp.control.XTextField xTextField29;
    // End of variables declaration//GEN-END:variables
    
}
