/*
 * CheckPaymentsInitPage.java
 *
 * Created on October 12, 2012, 9:24 AM
 */

package etracs2.tc.report;

import com.rameses.rcp.ui.annotations.StyleSheet;

/**
 *
 * @author  rameses
 */
@StyleSheet("etracs2/tc/report/CheckPaymentsInitPage.style")
public class CheckPaymentsInitPage extends javax.swing.JPanel {
    
    /** Creates new form CheckPaymentsInitPage */
    public CheckPaymentsInitPage() {
        initComponents(); 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xActionBar1 = new com.rameses.rcp.control.XActionBar();
        jPanel1 = new javax.swing.JPanel();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xComboBox4 = new com.rameses.rcp.control.XComboBox();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xRadio1 = new com.rameses.rcp.control.XRadio();
        formPanel5 = new com.rameses.rcp.util.FormPanel();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        xRadio2 = new com.rameses.rcp.control.XRadio();
        formPanel3 = new com.rameses.rcp.util.FormPanel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xRadio3 = new com.rameses.rcp.control.XRadio();
        formPanel4 = new com.rameses.rcp.util.FormPanel();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xDateField2 = new com.rameses.rcp.control.XDateField();

        setLayout(new java.awt.BorderLayout());

        xActionBar1.setBorder(new com.rameses.rcp.control.border.XUnderlineBorder());
        xActionBar1.setName("formActions");
        xActionBar1.setPadding(new java.awt.Insets(0, 5, 0, 0));
        add(xActionBar1, java.awt.BorderLayout.NORTH);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Initial Page");
        formPanel1.setBorder(xTitledBorder1);
        formPanel1.setPreferredSize(new java.awt.Dimension(444, 300));
        xComboBox4.setCaption("Collector");
        xComboBox4.setCellPadding(new java.awt.Insets(10, 0, 0, 0));
        xComboBox4.setExpression("#{name}");
        xComboBox4.setItems("collectorlist");
        xComboBox4.setName("collector");
        xComboBox4.setPreferredSize(new java.awt.Dimension(350, 22));
        formPanel1.add(xComboBox4);

        xTextField1.setCaption("Paid By");
        xTextField1.setCellPadding(new java.awt.Insets(0, 0, 5, 0));
        xTextField1.setName("paidby");
        xTextField1.setPreferredSize(new java.awt.Dimension(350, 19));
        formPanel1.add(xTextField1);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setTitle("Period");
        formPanel2.setBorder(xTitledBorder2);
        formPanel2.setCaptionBorder(null);
        formPanel2.setPreferredSize(new java.awt.Dimension(522, 180));
        formPanel2.setShowCaption(false);
        xRadio1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xRadio1.setText("Yearly");
        xRadio1.setCellPadding(new java.awt.Insets(0, 5, 0, 0));
        xRadio1.setFont(new java.awt.Font("Arial", 0, 12));
        xRadio1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xRadio1.setName("period");
        xRadio1.setOptionValue("Yearly");
        xRadio1.setPreferredSize(new java.awt.Dimension(400, 15));
        xRadio1.setShowCaption(false);
        formPanel2.add(xRadio1);

        formPanel5.setCaptionBorder(null);
        formPanel5.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        formPanel5.setPadding(new java.awt.Insets(2, 0, 2, 0));
        formPanel5.setPreferredSize(new java.awt.Dimension(0, 25));
        formPanel5.setShowCaption(false);
        xLabel4.setText("Year :");
        xLabel4.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xLabel4.setShowCaption(false);
        formPanel5.add(xLabel4);

        xNumberField2.setCaption("Year");
        xNumberField2.setCellPadding(new java.awt.Insets(0, 44, 0, 0));
        xNumberField2.setDepends(new String[] {"period"});
        xNumberField2.setFieldType(Integer.class);
        xNumberField2.setName("year");
        xNumberField2.setPreferredSize(new java.awt.Dimension(60, 19));
        xNumberField2.setRequired(true);
        xNumberField2.setShowCaption(false);
        formPanel5.add(xNumberField2);

        formPanel2.add(formPanel5);

        xRadio2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xRadio2.setText("Monthly");
        xRadio2.setCellPadding(new java.awt.Insets(0, 5, 0, 0));
        xRadio2.setFont(new java.awt.Font("Arial", 0, 12));
        xRadio2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xRadio2.setName("period");
        xRadio2.setOptionValue("Monthly");
        xRadio2.setPreferredSize(new java.awt.Dimension(400, 15));
        xRadio2.setShowCaption(false);
        formPanel2.add(xRadio2);

        formPanel3.setCaptionBorder(null);
        formPanel3.setCaptionPadding(new java.awt.Insets(0, 0, 0, 0));
        formPanel3.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        formPanel3.setPadding(new java.awt.Insets(2, 0, 2, 0));
        formPanel3.setPreferredSize(new java.awt.Dimension(0, 25));
        formPanel3.setShowCaption(false);
        xLabel2.setText("Year / Month :");
        xLabel2.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xLabel2.setShowCaption(false);
        formPanel3.add(xLabel2);

        xNumberField1.setCaption("Year");
        xNumberField1.setCellPadding(new java.awt.Insets(0, 6, 0, 0));
        xNumberField1.setDepends(new String[] {"period"});
        xNumberField1.setFieldType(Integer.class);
        xNumberField1.setName("year2");
        xNumberField1.setPreferredSize(new java.awt.Dimension(60, 19));
        xNumberField1.setRequired(true);
        xNumberField1.setShowCaption(false);
        formPanel3.add(xNumberField1);

        xComboBox1.setCaption("Month");
        xComboBox1.setDepends(new String[] {"period"});
        xComboBox1.setExpression("#{name}");
        xComboBox1.setItems("monthlist");
        xComboBox1.setName("month");
        xComboBox1.setPreferredSize(new java.awt.Dimension(126, 19));
        xComboBox1.setRequired(true);
        xComboBox1.setShowCaption(false);
        formPanel3.add(xComboBox1);

        formPanel2.add(formPanel3);

        xRadio3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xRadio3.setText("Date Ranged");
        xRadio3.setCellPadding(new java.awt.Insets(0, 5, 0, 0));
        xRadio3.setFont(new java.awt.Font("Arial", 0, 12));
        xRadio3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xRadio3.setName("period");
        xRadio3.setOptionValue("DateRanged");
        xRadio3.setPreferredSize(new java.awt.Dimension(400, 15));
        xRadio3.setShowCaption(false);
        formPanel2.add(xRadio3);

        formPanel4.setCaptionBorder(null);
        formPanel4.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        formPanel4.setPadding(new java.awt.Insets(2, 0, 2, 0));
        formPanel4.setPreferredSize(new java.awt.Dimension(0, 25));
        formPanel4.setShowCaption(false);
        xLabel3.setText("Date :");
        xLabel3.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xLabel3.setShowCaption(false);
        formPanel4.add(xLabel3);

        xDateField1.setCaption("Date From");
        xDateField1.setCellPadding(new java.awt.Insets(0, 47, 0, 0));
        xDateField1.setDepends(new String[] {"period"});
        xDateField1.setName("datefrom");
        xDateField1.setPreferredSize(new java.awt.Dimension(80, 19));
        xDateField1.setRequired(true);
        xDateField1.setShowCaption(false);
        formPanel4.add(xDateField1);

        xLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xLabel1.setText("To");
        xLabel1.setPreferredSize(new java.awt.Dimension(25, 19));
        xLabel1.setShowCaption(false);
        formPanel4.add(xLabel1);

        xDateField2.setCaption("Date To");
        xDateField2.setDepends(new String[] {"period"});
        xDateField2.setName("dateto");
        xDateField2.setPreferredSize(new java.awt.Dimension(80, 19));
        xDateField2.setRequired(true);
        xDateField2.setShowCaption(false);
        formPanel4.add(xDateField2);

        formPanel2.add(formPanel4);

        formPanel1.add(formPanel2);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        add(jPanel1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.util.FormPanel formPanel2;
    private com.rameses.rcp.util.FormPanel formPanel3;
    private com.rameses.rcp.util.FormPanel formPanel4;
    private com.rameses.rcp.util.FormPanel formPanel5;
    private javax.swing.JPanel jPanel1;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox4;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    private com.rameses.rcp.control.XRadio xRadio1;
    private com.rameses.rcp.control.XRadio xRadio2;
    private com.rameses.rcp.control.XRadio xRadio3;
    private com.rameses.rcp.control.XTextField xTextField1;
    // End of variables declaration//GEN-END:variables
    
}
