/*
 * PageFlowForm.java
 *
 * Created on November 5, 2012, 9:48 PM
 */

package shared.pageflow;

/**
 *
 * @author  Elmo
 */
public class PageFlowForm extends javax.swing.JPanel {
    
    /** Creates new form PageFlowForm */
    public PageFlowForm() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xActionBar1 = new com.rameses.rcp.control.XActionBar();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        xLabel1.setBackground(new java.awt.Color(255, 255, 255));
        xLabel1.setFont(new java.awt.Font("Arial", 1, 18));
        xLabel1.setName("pageTitle");
        xLabel1.setOpaque(true);
        jPanel2.add(xLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        xActionBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xActionBar1.setDynamic(true);
        xActionBar1.setName("actions");
        xActionBar1.setPreferredSize(new java.awt.Dimension(61, 35));
        jPanel1.add(xActionBar1, java.awt.BorderLayout.SOUTH);

        add(jPanel1, java.awt.BorderLayout.NORTH);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XLabel xLabel1;
    // End of variables declaration//GEN-END:variables
    
}
